import type { Metadata } from "next";
import { App as AntdApp } from "antd";
import "antd/dist/reset.css";
import ClientProviders from "@/hooks";

export const metadata: Metadata = {
  title: "Teste",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ClientProviders>
          <AntdApp>{children}</AntdApp>
        </ClientProviders>
      </body>
    </html>
  );
}
